// GENERATED by: npx supabase gen types typescript --linked --schema public. Do not edit by hand.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.18"
  }
  public: {
    Tables: {
      audit_log: {
        Row: {
          action: string
          actor_id: string | null
          created_at: string
          entity: string
          entity_id: string | null
          id: number
          metadata: Json
        }
        Insert: {
          action: string
          actor_id?: string | null
          created_at?: string
          entity: string
          entity_id?: string | null
          id?: never
          metadata?: Json
        }
        Update: {
          action?: string
          actor_id?: string | null
          created_at?: string
          entity?: string
          entity_id?: string | null
          id?: never
          metadata?: Json
        }
        Relationships: []
      }
      deidentified_observations: {
        Row: {
          age_band: Database["public"]["Enums"]["age_band"]
          case_count: number
          created_at: string
          id: string
          is_synthetic: boolean
          observed_date: string
          privacy_level: Database["public"]["Enums"]["privacy_level"]
          region_id: string
          report_id: string | null
          report_type: Database["public"]["Enums"]["report_type"]
          severity: Database["public"]["Enums"]["report_severity"]
          source_type: Database["public"]["Enums"]["source_type"]
          symptom_codes: string[]
          syndrome: Database["public"]["Enums"]["syndrome_category"]
        }
        Insert: {
          age_band: Database["public"]["Enums"]["age_band"]
          case_count: number
          created_at?: string
          id?: string
          is_synthetic?: boolean
          observed_date: string
          privacy_level?: Database["public"]["Enums"]["privacy_level"]
          region_id: string
          report_id?: string | null
          report_type: Database["public"]["Enums"]["report_type"]
          severity: Database["public"]["Enums"]["report_severity"]
          source_type: Database["public"]["Enums"]["source_type"]
          symptom_codes?: string[]
          syndrome: Database["public"]["Enums"]["syndrome_category"]
        }
        Update: {
          age_band?: Database["public"]["Enums"]["age_band"]
          case_count?: number
          created_at?: string
          id?: string
          is_synthetic?: boolean
          observed_date?: string
          privacy_level?: Database["public"]["Enums"]["privacy_level"]
          region_id?: string
          report_id?: string | null
          report_type?: Database["public"]["Enums"]["report_type"]
          severity?: Database["public"]["Enums"]["report_severity"]
          source_type?: Database["public"]["Enums"]["source_type"]
          symptom_codes?: string[]
          syndrome?: Database["public"]["Enums"]["syndrome_category"]
        }
        Relationships: [
          {
            foreignKeyName: "deidentified_observations_region_id_fkey"
            columns: ["region_id"]
            isOneToOne: false
            referencedRelation: "regions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "deidentified_observations_report_id_fkey"
            columns: ["report_id"]
            isOneToOne: true
            referencedRelation: "health_reports"
            referencedColumns: ["id"]
          },
        ]
      }
      detection_methods: {
        Row: {
          active: boolean
          code: string
          created_at: string
          description: string
        }
        Insert: {
          active?: boolean
          code: string
          created_at?: string
          description: string
        }
        Update: {
          active?: boolean
          code?: string
          created_at?: string
          description?: string
        }
        Relationships: []
      }
      evidence_items: {
        Row: {
          citation: string | null
          content_hash: string | null
          created_at: string
          created_by: string | null
          id: string
          language: string | null
          publication_date: string | null
          publisher: string
          reference_url: string | null
          source_type: Database["public"]["Enums"]["evidence_source_type"]
          title: string
          trust_level: Database["public"]["Enums"]["evidence_trust_level"]
          updated_at: string
          verified_at: string | null
          verified_by: string | null
        }
        Insert: {
          citation?: string | null
          content_hash?: string | null
          created_at?: string
          created_by?: string | null
          id?: string
          language?: string | null
          publication_date?: string | null
          publisher: string
          reference_url?: string | null
          source_type: Database["public"]["Enums"]["evidence_source_type"]
          title: string
          trust_level?: Database["public"]["Enums"]["evidence_trust_level"]
          updated_at?: string
          verified_at?: string | null
          verified_by?: string | null
        }
        Update: {
          citation?: string | null
          content_hash?: string | null
          created_at?: string
          created_by?: string | null
          id?: string
          language?: string | null
          publication_date?: string | null
          publisher?: string
          reference_url?: string | null
          source_type?: Database["public"]["Enums"]["evidence_source_type"]
          title?: string
          trust_level?: Database["public"]["Enums"]["evidence_trust_level"]
          updated_at?: string
          verified_at?: string | null
          verified_by?: string | null
        }
        Relationships: []
      }
      health_reports: {
        Row: {
          age_band: Database["public"]["Enums"]["age_band"]
          case_count: number
          client_submission_id: string
          created_at: string
          free_text: string | null
          id: string
          language: string
          observed_at: string
          privacy_level: Database["public"]["Enums"]["privacy_level"]
          processing_status: Database["public"]["Enums"]["processing_status"]
          region_id: string
          report_type: Database["public"]["Enums"]["report_type"]
          severity: Database["public"]["Enums"]["report_severity"]
          source_type: Database["public"]["Enums"]["source_type"]
          submitted_by: string | null
          symptom_codes: string[]
          syndrome: Database["public"]["Enums"]["syndrome_category"]
          synthetic_batch: string | null
          updated_at: string
        }
        Insert: {
          age_band?: Database["public"]["Enums"]["age_band"]
          case_count?: number
          client_submission_id?: string
          created_at?: string
          free_text?: string | null
          id?: string
          language?: string
          observed_at: string
          privacy_level?: Database["public"]["Enums"]["privacy_level"]
          processing_status?: Database["public"]["Enums"]["processing_status"]
          region_id: string
          report_type?: Database["public"]["Enums"]["report_type"]
          severity?: Database["public"]["Enums"]["report_severity"]
          source_type: Database["public"]["Enums"]["source_type"]
          submitted_by?: string | null
          symptom_codes?: string[]
          syndrome: Database["public"]["Enums"]["syndrome_category"]
          synthetic_batch?: string | null
          updated_at?: string
        }
        Update: {
          age_band?: Database["public"]["Enums"]["age_band"]
          case_count?: number
          client_submission_id?: string
          created_at?: string
          free_text?: string | null
          id?: string
          language?: string
          observed_at?: string
          privacy_level?: Database["public"]["Enums"]["privacy_level"]
          processing_status?: Database["public"]["Enums"]["processing_status"]
          region_id?: string
          report_type?: Database["public"]["Enums"]["report_type"]
          severity?: Database["public"]["Enums"]["report_severity"]
          source_type?: Database["public"]["Enums"]["source_type"]
          submitted_by?: string | null
          symptom_codes?: string[]
          syndrome?: Database["public"]["Enums"]["syndrome_category"]
          synthetic_batch?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "health_reports_region_id_fkey"
            columns: ["region_id"]
            isOneToOne: false
            referencedRelation: "regions"
            referencedColumns: ["id"]
          },
        ]
      }
      privacy_settings: {
        Row: {
          description: string
          key: string
          updated_at: string
          value_int: number
        }
        Insert: {
          description: string
          key: string
          updated_at?: string
          value_int: number
        }
        Update: {
          description?: string
          key?: string
          updated_at?: string
          value_int?: number
        }
        Relationships: []
      }
      profiles: {
        Row: {
          created_at: string
          display_name: string | null
          id: string
          preferred_language: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          display_name?: string | null
          id: string
          preferred_language?: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          display_name?: string | null
          id?: string
          preferred_language?: string
          updated_at?: string
        }
        Relationships: []
      }
      regions: {
        Row: {
          active: boolean
          administrative_code: string | null
          created_at: string
          id: string
          is_synthetic: boolean
          name: string
          name_local: Json
          parent_region_id: string | null
          region_type: Database["public"]["Enums"]["region_type"]
          updated_at: string
        }
        Insert: {
          active?: boolean
          administrative_code?: string | null
          created_at?: string
          id?: string
          is_synthetic?: boolean
          name: string
          name_local?: Json
          parent_region_id?: string | null
          region_type: Database["public"]["Enums"]["region_type"]
          updated_at?: string
        }
        Update: {
          active?: boolean
          administrative_code?: string | null
          created_at?: string
          id?: string
          is_synthetic?: boolean
          name?: string
          name_local?: Json
          parent_region_id?: string | null
          region_type?: Database["public"]["Enums"]["region_type"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "regions_parent_region_id_fkey"
            columns: ["parent_region_id"]
            isOneToOne: false
            referencedRelation: "regions"
            referencedColumns: ["id"]
          },
        ]
      }
      report_aggregates: {
        Row: {
          case_count: number
          computed_at: string
          id: string
          min_cell_size_applied: number
          observed_date: string
          privacy_level: Database["public"]["Enums"]["privacy_level"]
          region_id: string
          report_count: number
          suppressed: boolean
          syndrome: Database["public"]["Enums"]["syndrome_category"]
        }
        Insert: {
          case_count: number
          computed_at?: string
          id?: string
          min_cell_size_applied: number
          observed_date: string
          privacy_level?: Database["public"]["Enums"]["privacy_level"]
          region_id: string
          report_count: number
          suppressed: boolean
          syndrome: Database["public"]["Enums"]["syndrome_category"]
        }
        Update: {
          case_count?: number
          computed_at?: string
          id?: string
          min_cell_size_applied?: number
          observed_date?: string
          privacy_level?: Database["public"]["Enums"]["privacy_level"]
          region_id?: string
          report_count?: number
          suppressed?: boolean
          syndrome?: Database["public"]["Enums"]["syndrome_category"]
        }
        Relationships: [
          {
            foreignKeyName: "report_aggregates_region_id_fkey"
            columns: ["region_id"]
            isOneToOne: false
            referencedRelation: "regions"
            referencedColumns: ["id"]
          },
        ]
      }
      report_signal_links: {
        Row: {
          aggregate_id: string | null
          created_at: string
          id: string
          observation_id: string | null
          signal_candidate_id: string
        }
        Insert: {
          aggregate_id?: string | null
          created_at?: string
          id?: string
          observation_id?: string | null
          signal_candidate_id: string
        }
        Update: {
          aggregate_id?: string | null
          created_at?: string
          id?: string
          observation_id?: string | null
          signal_candidate_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "report_signal_links_aggregate_id_fkey"
            columns: ["aggregate_id"]
            isOneToOne: false
            referencedRelation: "report_aggregates"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "report_signal_links_observation_id_fkey"
            columns: ["observation_id"]
            isOneToOne: false
            referencedRelation: "deidentified_observations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "report_signal_links_signal_candidate_id_fkey"
            columns: ["signal_candidate_id"]
            isOneToOne: false
            referencedRelation: "signal_candidates"
            referencedColumns: ["id"]
          },
        ]
      }
      signal_candidates: {
        Row: {
          baseline_value: number | null
          confidence: number | null
          created_at: string
          created_by: string | null
          detection_method: string
          deviation: number | null
          explanation: string | null
          id: string
          minimum_sample_count: number
          observed_value: number
          origin: Database["public"]["Enums"]["signal_origin"]
          region_id: string
          resolved_at: string | null
          review_note: string | null
          reviewed_at: string | null
          reviewed_by: string | null
          sample_count: number | null
          signal_score: number | null
          status: Database["public"]["Enums"]["signal_status"]
          syndrome: Database["public"]["Enums"]["syndrome_category"]
          time_window_end: string
          time_window_start: string
          updated_at: string
          verification_status: Database["public"]["Enums"]["verification_status"]
        }
        Insert: {
          baseline_value?: number | null
          confidence?: number | null
          created_at?: string
          created_by?: string | null
          detection_method?: string
          deviation?: number | null
          explanation?: string | null
          id?: string
          minimum_sample_count?: number
          observed_value: number
          origin?: Database["public"]["Enums"]["signal_origin"]
          region_id: string
          resolved_at?: string | null
          review_note?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          sample_count?: number | null
          signal_score?: number | null
          status?: Database["public"]["Enums"]["signal_status"]
          syndrome: Database["public"]["Enums"]["syndrome_category"]
          time_window_end: string
          time_window_start: string
          updated_at?: string
          verification_status?: Database["public"]["Enums"]["verification_status"]
        }
        Update: {
          baseline_value?: number | null
          confidence?: number | null
          created_at?: string
          created_by?: string | null
          detection_method?: string
          deviation?: number | null
          explanation?: string | null
          id?: string
          minimum_sample_count?: number
          observed_value?: number
          origin?: Database["public"]["Enums"]["signal_origin"]
          region_id?: string
          resolved_at?: string | null
          review_note?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          sample_count?: number | null
          signal_score?: number | null
          status?: Database["public"]["Enums"]["signal_status"]
          syndrome?: Database["public"]["Enums"]["syndrome_category"]
          time_window_end?: string
          time_window_start?: string
          updated_at?: string
          verification_status?: Database["public"]["Enums"]["verification_status"]
        }
        Relationships: [
          {
            foreignKeyName: "signal_candidates_detection_method_fkey"
            columns: ["detection_method"]
            isOneToOne: false
            referencedRelation: "detection_methods"
            referencedColumns: ["code"]
          },
          {
            foreignKeyName: "signal_candidates_region_id_fkey"
            columns: ["region_id"]
            isOneToOne: false
            referencedRelation: "regions"
            referencedColumns: ["id"]
          },
        ]
      }
      signal_evidence: {
        Row: {
          created_at: string
          evidence_item_id: string
          relevance_note: string | null
          signal_candidate_id: string
        }
        Insert: {
          created_at?: string
          evidence_item_id: string
          relevance_note?: string | null
          signal_candidate_id: string
        }
        Update: {
          created_at?: string
          evidence_item_id?: string
          relevance_note?: string | null
          signal_candidate_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "signal_evidence_evidence_item_id_fkey"
            columns: ["evidence_item_id"]
            isOneToOne: false
            referencedRelation: "evidence_items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "signal_evidence_signal_candidate_id_fkey"
            columns: ["signal_candidate_id"]
            isOneToOne: false
            referencedRelation: "signal_candidates"
            referencedColumns: ["id"]
          },
        ]
      }
      symptom_terms: {
        Row: {
          active: boolean
          code: string
          created_at: string
          label_en: string
          label_hi: string | null
          label_or: string | null
          syndrome_hint: Database["public"]["Enums"]["syndrome_category"] | null
        }
        Insert: {
          active?: boolean
          code: string
          created_at?: string
          label_en: string
          label_hi?: string | null
          label_or?: string | null
          syndrome_hint?:
            | Database["public"]["Enums"]["syndrome_category"]
            | null
        }
        Update: {
          active?: boolean
          code?: string
          created_at?: string
          label_en?: string
          label_hi?: string | null
          label_or?: string | null
          syndrome_hint?:
            | Database["public"]["Enums"]["syndrome_category"]
            | null
        }
        Relationships: []
      }
      user_roles: {
        Row: {
          created_at: string
          granted_by: string | null
          id: string
          region_id: string | null
          role: Database["public"]["Enums"]["app_role"]
          user_id: string
        }
        Insert: {
          created_at?: string
          granted_by?: string | null
          id?: string
          region_id?: string | null
          role: Database["public"]["Enums"]["app_role"]
          user_id: string
        }
        Update: {
          created_at?: string
          granted_by?: string | null
          id?: string
          region_id?: string | null
          role?: Database["public"]["Enums"]["app_role"]
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_roles_region_id_fkey"
            columns: ["region_id"]
            isOneToOne: false
            referencedRelation: "regions"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      admin_list_users: {
        Args: { _limit?: number; _offset?: number }
        Returns: {
          created_at: string
          display_name: string
          email: string
          roles: Database["public"]["Enums"]["app_role"][]
          user_id: string
        }[]
      }
      admin_set_user_region_scope: {
        Args: {
          _region_id: string
          _role: Database["public"]["Enums"]["app_role"]
          _target: string
        }
        Returns: undefined
      }
      admin_set_user_role: {
        Args: {
          _grant: boolean
          _role: Database["public"]["Enums"]["app_role"]
          _target: string
        }
        Returns: undefined
      }
      apply_report_retention: { Args: never; Returns: Json }
      deidentify_pending_reports: { Args: { _limit?: number }; Returns: number }
      get_report_aggregates: {
        Args: { _from: string; _region_id: string; _to: string }
        Returns: {
          case_count: number
          observed_date: string
          region_id: string
          report_count: number
          suppressed: boolean
          syndrome: Database["public"]["Enums"]["syndrome_category"]
        }[]
      }
      has_role: {
        Args: {
          _role: Database["public"]["Enums"]["app_role"]
          _user_id: string
        }
        Returns: boolean
      }
      is_region_in_scope: {
        Args: {
          _region_id: string
          _role: Database["public"]["Enums"]["app_role"]
          _user_id: string
        }
        Returns: boolean
      }
      refresh_report_aggregates: {
        Args: { _from: string; _to: string }
        Returns: number
      }
      region_subtree: {
        Args: { _root: string }
        Returns: {
          id: string
        }[]
      }
      review_signal_candidate: {
        Args: {
          _new_status: Database["public"]["Enums"]["signal_status"]
          _note?: string
          _signal_id: string
          _verification: Database["public"]["Enums"]["verification_status"]
        }
        Returns: {
          baseline_value: number | null
          confidence: number | null
          created_at: string
          created_by: string | null
          detection_method: string
          deviation: number | null
          explanation: string | null
          id: string
          minimum_sample_count: number
          observed_value: number
          origin: Database["public"]["Enums"]["signal_origin"]
          region_id: string
          resolved_at: string | null
          review_note: string | null
          reviewed_at: string | null
          reviewed_by: string | null
          sample_count: number | null
          signal_score: number | null
          status: Database["public"]["Enums"]["signal_status"]
          syndrome: Database["public"]["Enums"]["syndrome_category"]
          time_window_end: string
          time_window_start: string
          updated_at: string
          verification_status: Database["public"]["Enums"]["verification_status"]
        }
        SetofOptions: {
          from: "*"
          to: "signal_candidates"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      write_audit: {
        Args: {
          _action: string
          _actor: string
          _entity: string
          _entity_id: string
          _metadata: Json
        }
        Returns: undefined
      }
    }
    Enums: {
      age_band:
        | "age_0_4"
        | "age_5_17"
        | "age_18_44"
        | "age_45_59"
        | "age_60_plus"
        | "age_unknown"
      app_role: "citizen" | "clinician" | "officer" | "admin"
      evidence_source_type:
        | "guideline"
        | "government_advisory"
        | "peer_reviewed"
        | "situation_report"
        | "dataset"
        | "other"
      evidence_trust_level: "unreviewed" | "reviewed" | "trusted"
      privacy_level: "raw" | "deidentified" | "aggregated"
      processing_status: "received" | "validated" | "deidentified" | "rejected"
      region_type: "country" | "state" | "district" | "block" | "locality"
      report_severity: "unknown" | "mild" | "moderate" | "severe"
      report_type: "individual_observation" | "aggregate_count"
      signal_origin: "system_detector" | "officer_manual" | "imported"
      signal_status:
        | "candidate"
        | "under_review"
        | "verified"
        | "monitoring"
        | "resolved"
        | "dismissed"
      source_type:
        | "citizen"
        | "clinician"
        | "health_facility"
        | "public_health_officer"
        | "survey"
        | "environmental"
        | "imported_dataset"
        | "system_generated"
      syndrome_category:
        | "acute_diarrhoeal_illness"
        | "fever"
        | "fever_with_rash"
        | "jaundice"
        | "respiratory_illness"
        | "other"
        | "unknown"
      verification_status:
        | "unverified"
        | "in_progress"
        | "supported"
        | "not_supported"
        | "inconclusive"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      age_band: [
        "age_0_4",
        "age_5_17",
        "age_18_44",
        "age_45_59",
        "age_60_plus",
        "age_unknown",
      ],
      app_role: ["citizen", "clinician", "officer", "admin"],
      evidence_source_type: [
        "guideline",
        "government_advisory",
        "peer_reviewed",
        "situation_report",
        "dataset",
        "other",
      ],
      evidence_trust_level: ["unreviewed", "reviewed", "trusted"],
      privacy_level: ["raw", "deidentified", "aggregated"],
      processing_status: ["received", "validated", "deidentified", "rejected"],
      region_type: ["country", "state", "district", "block", "locality"],
      report_severity: ["unknown", "mild", "moderate", "severe"],
      report_type: ["individual_observation", "aggregate_count"],
      signal_origin: ["system_detector", "officer_manual", "imported"],
      signal_status: [
        "candidate",
        "under_review",
        "verified",
        "monitoring",
        "resolved",
        "dismissed",
      ],
      source_type: [
        "citizen",
        "clinician",
        "health_facility",
        "public_health_officer",
        "survey",
        "environmental",
        "imported_dataset",
        "system_generated",
      ],
      syndrome_category: [
        "acute_diarrhoeal_illness",
        "fever",
        "fever_with_rash",
        "jaundice",
        "respiratory_illness",
        "other",
        "unknown",
      ],
      verification_status: [
        "unverified",
        "in_progress",
        "supported",
        "not_supported",
        "inconclusive",
      ],
    },
  },
} as const
