// GENERATED by: npx supabase gen types typescript --linked --schema public. Do not edit by hand.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.18"
  }
  public: {
    Tables: {
      audit_log: {
        Row: {
          action: string
          actor_id: string | null
          created_at: string
          entity: string
          entity_id: string | null
          id: number
          metadata: Json
        }
        Insert: {
          action: string
          actor_id?: string | null
          created_at?: string
          entity: string
          entity_id?: string | null
          id?: never
          metadata?: Json
        }
        Update: {
          action?: string
          actor_id?: string | null
          created_at?: string
          entity?: string
          entity_id?: string | null
          id?: never
          metadata?: Json
        }
        Relationships: []
      }
      corpus_snapshots: {
        Row: {
          chunk_count: number
          corpus_hash: string
          corpus_version: string
          created_at: string
          id: string
          includes_synthetic: boolean
          is_active: boolean
          item_count: number
          notes: string | null
        }
        Insert: {
          chunk_count: number
          corpus_hash: string
          corpus_version: string
          created_at?: string
          id?: string
          includes_synthetic: boolean
          is_active?: boolean
          item_count: number
          notes?: string | null
        }
        Update: {
          chunk_count?: number
          corpus_hash?: string
          corpus_version?: string
          created_at?: string
          id?: string
          includes_synthetic?: boolean
          is_active?: boolean
          item_count?: number
          notes?: string | null
        }
        Relationships: []
      }
      deidentified_observations: {
        Row: {
          age_band: Database["public"]["Enums"]["age_band"]
          case_count: number
          created_at: string
          id: string
          is_synthetic: boolean
          observed_date: string
          privacy_level: Database["public"]["Enums"]["privacy_level"]
          region_id: string
          report_id: string | null
          report_type: Database["public"]["Enums"]["report_type"]
          severity: Database["public"]["Enums"]["report_severity"]
          source_type: Database["public"]["Enums"]["source_type"]
          symptom_codes: string[]
          syndrome: Database["public"]["Enums"]["syndrome_category"]
        }
        Insert: {
          age_band: Database["public"]["Enums"]["age_band"]
          case_count: number
          created_at?: string
          id?: string
          is_synthetic?: boolean
          observed_date: string
          privacy_level?: Database["public"]["Enums"]["privacy_level"]
          region_id: string
          report_id?: string | null
          report_type: Database["public"]["Enums"]["report_type"]
          severity: Database["public"]["Enums"]["report_severity"]
          source_type: Database["public"]["Enums"]["source_type"]
          symptom_codes?: string[]
          syndrome: Database["public"]["Enums"]["syndrome_category"]
        }
        Update: {
          age_band?: Database["public"]["Enums"]["age_band"]
          case_count?: number
          created_at?: string
          id?: string
          is_synthetic?: boolean
          observed_date?: string
          privacy_level?: Database["public"]["Enums"]["privacy_level"]
          region_id?: string
          report_id?: string | null
          report_type?: Database["public"]["Enums"]["report_type"]
          severity?: Database["public"]["Enums"]["report_severity"]
          source_type?: Database["public"]["Enums"]["source_type"]
          symptom_codes?: string[]
          syndrome?: Database["public"]["Enums"]["syndrome_category"]
        }
        Relationships: [
          {
            foreignKeyName: "deidentified_observations_region_id_fkey"
            columns: ["region_id"]
            isOneToOne: false
            referencedRelation: "regions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "deidentified_observations_report_id_fkey"
            columns: ["report_id"]
            isOneToOne: true
            referencedRelation: "health_reports"
            referencedColumns: ["id"]
          },
        ]
      }
      detection_methods: {
        Row: {
          active: boolean
          code: string
          created_at: string
          description: string
        }
        Insert: {
          active?: boolean
          code: string
          created_at?: string
          description: string
        }
        Update: {
          active?: boolean
          code?: string
          created_at?: string
          description?: string
        }
        Relationships: []
      }
      detector_findings: {
        Row: {
          as_of_date: string
          block_ids: string[]
          candidate_id: string | null
          created_at: string
          decision: string
          district_id: string
          expected: number
          failed_gates: string[]
          id: string
          observed: number | null
          p_value: number
          ratio: number | null
          run_id: string
          scope: string
          score: number | null
          syndrome: Database["public"]["Enums"]["syndrome_category"]
          window_days: number
        }
        Insert: {
          as_of_date: string
          block_ids: string[]
          candidate_id?: string | null
          created_at?: string
          decision: string
          district_id: string
          expected: number
          failed_gates?: string[]
          id?: string
          observed?: number | null
          p_value: number
          ratio?: number | null
          run_id: string
          scope: string
          score?: number | null
          syndrome: Database["public"]["Enums"]["syndrome_category"]
          window_days: number
        }
        Update: {
          as_of_date?: string
          block_ids?: string[]
          candidate_id?: string | null
          created_at?: string
          decision?: string
          district_id?: string
          expected?: number
          failed_gates?: string[]
          id?: string
          observed?: number | null
          p_value?: number
          ratio?: number | null
          run_id?: string
          scope?: string
          score?: number | null
          syndrome?: Database["public"]["Enums"]["syndrome_category"]
          window_days?: number
        }
        Relationships: [
          {
            foreignKeyName: "detector_findings_candidate_id_fkey"
            columns: ["candidate_id"]
            isOneToOne: false
            referencedRelation: "signal_candidates"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "detector_findings_district_id_fkey"
            columns: ["district_id"]
            isOneToOne: false
            referencedRelation: "regions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "detector_findings_run_id_fkey"
            columns: ["run_id"]
            isOneToOne: false
            referencedRelation: "detector_runs"
            referencedColumns: ["id"]
          },
        ]
      }
      detector_runs: {
        Row: {
          as_of_from: string | null
          as_of_to: string | null
          code_version: string | null
          config: Json
          config_hash: string
          data_from: string
          data_to: string
          detector_name: string
          detector_version: string
          error: string | null
          evidence_floor: number
          finished_at: string | null
          id: string
          input_hash: string | null
          input_row_count: number
          method_code: string
          mode: string
          privacy_k_applied: number
          started_at: string
          stats: Json
          status: string
        }
        Insert: {
          as_of_from?: string | null
          as_of_to?: string | null
          code_version?: string | null
          config: Json
          config_hash: string
          data_from: string
          data_to: string
          detector_name: string
          detector_version: string
          error?: string | null
          evidence_floor: number
          finished_at?: string | null
          id?: string
          input_hash?: string | null
          input_row_count?: number
          method_code: string
          mode: string
          privacy_k_applied: number
          started_at?: string
          stats?: Json
          status?: string
        }
        Update: {
          as_of_from?: string | null
          as_of_to?: string | null
          code_version?: string | null
          config?: Json
          config_hash?: string
          data_from?: string
          data_to?: string
          detector_name?: string
          detector_version?: string
          error?: string | null
          evidence_floor?: number
          finished_at?: string | null
          id?: string
          input_hash?: string | null
          input_row_count?: number
          method_code?: string
          mode?: string
          privacy_k_applied?: number
          started_at?: string
          stats?: Json
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "detector_runs_method_code_fkey"
            columns: ["method_code"]
            isOneToOne: false
            referencedRelation: "detection_methods"
            referencedColumns: ["code"]
          },
        ]
      }
      evaluation_event_results: {
        Row: {
          credited_date: string | null
          decoy_alerted: boolean | null
          delay_days: number | null
          detected: boolean
          evaluable: boolean
          evaluation_run_id: string
          event_id: string
          gate_reasons: string[]
          id: string
          kind: string
          late_detected: boolean
          localization: Json | null
        }
        Insert: {
          credited_date?: string | null
          decoy_alerted?: boolean | null
          delay_days?: number | null
          detected: boolean
          evaluable: boolean
          evaluation_run_id: string
          event_id: string
          gate_reasons?: string[]
          id?: string
          kind: string
          late_detected?: boolean
          localization?: Json | null
        }
        Update: {
          credited_date?: string | null
          decoy_alerted?: boolean | null
          delay_days?: number | null
          detected?: boolean
          evaluable?: boolean
          evaluation_run_id?: string
          event_id?: string
          gate_reasons?: string[]
          id?: string
          kind?: string
          late_detected?: boolean
          localization?: Json | null
        }
        Relationships: [
          {
            foreignKeyName: "evaluation_event_results_evaluation_run_id_fkey"
            columns: ["evaluation_run_id"]
            isOneToOne: false
            referencedRelation: "evaluation_runs"
            referencedColumns: ["id"]
          },
        ]
      }
      evaluation_runs: {
        Row: {
          config_hash: string
          created_at: string
          dataset_hash: string | null
          dataset_ref: string
          detector_version: string
          disclaimer: string
          ground_truth_hash: string | null
          id: string
          kind: string
          matching_rules_version: string
          metrics: Json
          n_datasets: number
        }
        Insert: {
          config_hash: string
          created_at?: string
          dataset_hash?: string | null
          dataset_ref: string
          detector_version: string
          disclaimer?: string
          ground_truth_hash?: string | null
          id?: string
          kind: string
          matching_rules_version: string
          metrics: Json
          n_datasets: number
        }
        Update: {
          config_hash?: string
          created_at?: string
          dataset_hash?: string | null
          dataset_ref?: string
          detector_version?: string
          disclaimer?: string
          ground_truth_hash?: string | null
          id?: string
          kind?: string
          matching_rules_version?: string
          metrics?: Json
          n_datasets?: number
        }
        Relationships: []
      }
      evidence_bundle_items: {
        Row: {
          bundle_id: string
          chunk_id: string
          citation_id: string
          evidence_version_id: string
          facet: string
          id: string
          rank: number
          score_components: Json
          why: Json
        }
        Insert: {
          bundle_id: string
          chunk_id: string
          citation_id: string
          evidence_version_id: string
          facet: string
          id?: string
          rank: number
          score_components?: Json
          why?: Json
        }
        Update: {
          bundle_id?: string
          chunk_id?: string
          citation_id?: string
          evidence_version_id?: string
          facet?: string
          id?: string
          rank?: number
          score_components?: Json
          why?: Json
        }
        Relationships: [
          {
            foreignKeyName: "evidence_bundle_items_bundle_id_fkey"
            columns: ["bundle_id"]
            isOneToOne: false
            referencedRelation: "evidence_bundles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "evidence_bundle_items_chunk_id_fkey"
            columns: ["chunk_id"]
            isOneToOne: false
            referencedRelation: "evidence_chunks"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "evidence_bundle_items_evidence_version_id_fkey"
            columns: ["evidence_version_id"]
            isOneToOne: false
            referencedRelation: "evidence_versions"
            referencedColumns: ["id"]
          },
        ]
      }
      evidence_bundles: {
        Row: {
          bundle: Json
          bundle_hash: string
          conflict_count: number
          created_at: string
          gap_count: number
          id: string
          item_count: number
          retrieval_run_id: string
          schema_version: string
          signal_candidate_id: string
        }
        Insert: {
          bundle: Json
          bundle_hash: string
          conflict_count?: number
          created_at?: string
          gap_count?: number
          id?: string
          item_count?: number
          retrieval_run_id: string
          schema_version: string
          signal_candidate_id: string
        }
        Update: {
          bundle?: Json
          bundle_hash?: string
          conflict_count?: number
          created_at?: string
          gap_count?: number
          id?: string
          item_count?: number
          retrieval_run_id?: string
          schema_version?: string
          signal_candidate_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "evidence_bundles_retrieval_run_id_fkey"
            columns: ["retrieval_run_id"]
            isOneToOne: false
            referencedRelation: "retrieval_runs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "evidence_bundles_signal_candidate_id_fkey"
            columns: ["signal_candidate_id"]
            isOneToOne: false
            referencedRelation: "signal_candidates"
            referencedColumns: ["id"]
          },
        ]
      }
      evidence_chunks: {
        Row: {
          chunk_hash: string
          created_at: string
          id: string
          kind: string
          language: string
          ordinal: number
          text: string
          version_id: string
        }
        Insert: {
          chunk_hash: string
          created_at?: string
          id?: string
          kind: string
          language?: string
          ordinal: number
          text: string
          version_id: string
        }
        Update: {
          chunk_hash?: string
          created_at?: string
          id?: string
          kind?: string
          language?: string
          ordinal?: number
          text?: string
          version_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "evidence_chunks_version_id_fkey"
            columns: ["version_id"]
            isOneToOne: false
            referencedRelation: "evidence_versions"
            referencedColumns: ["id"]
          },
        ]
      }
      evidence_evaluation_results: {
        Row: {
          id: string
          metrics: Json
          passed: boolean
          run_id: string
          scenario_id: string
        }
        Insert: {
          id?: string
          metrics?: Json
          passed: boolean
          run_id: string
          scenario_id: string
        }
        Update: {
          id?: string
          metrics?: Json
          passed?: boolean
          run_id?: string
          scenario_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "evidence_evaluation_results_run_id_fkey"
            columns: ["run_id"]
            isOneToOne: false
            referencedRelation: "evidence_evaluation_runs"
            referencedColumns: ["id"]
          },
        ]
      }
      evidence_evaluation_runs: {
        Row: {
          corpus_hash: string
          created_at: string
          disclaimer: string
          id: string
          kind: string
          metrics: Json
          n_scenarios: number
          prompt_version: string | null
          retrieval_config_hash: string
          scenario_set_ref: string
        }
        Insert: {
          corpus_hash: string
          created_at?: string
          disclaimer?: string
          id?: string
          kind: string
          metrics: Json
          n_scenarios: number
          prompt_version?: string | null
          retrieval_config_hash: string
          scenario_set_ref: string
        }
        Update: {
          corpus_hash?: string
          created_at?: string
          disclaimer?: string
          id?: string
          kind?: string
          metrics?: Json
          n_scenarios?: number
          prompt_version?: string | null
          retrieval_config_hash?: string
          scenario_set_ref?: string
        }
        Relationships: []
      }
      evidence_items: {
        Row: {
          canonical_id: string | null
          citation: string | null
          content_hash: string | null
          created_at: string
          created_by: string | null
          evidence_kind: Database["public"]["Enums"]["evidence_kind"] | null
          geo_region_id: string | null
          geo_scope: Database["public"]["Enums"]["evidence_geo_scope"] | null
          id: string
          is_synthetic: boolean
          language: string | null
          licence: string | null
          publication_date: string | null
          publisher: string
          reference_url: string | null
          review_due: string | null
          source_class: Database["public"]["Enums"]["evidence_source_class"]
          source_domain: string | null
          source_type: Database["public"]["Enums"]["evidence_source_type"]
          status: Database["public"]["Enums"]["evidence_status"]
          supersedes_id: string | null
          syndromes: Database["public"]["Enums"]["syndrome_category"][]
          title: string
          topics: string[]
          trust_level: Database["public"]["Enums"]["evidence_trust_level"]
          updated_at: string
          valid_from: string | null
          valid_until: string | null
          verification_basis: string[]
          verified_at: string | null
          verified_by: string | null
        }
        Insert: {
          canonical_id?: string | null
          citation?: string | null
          content_hash?: string | null
          created_at?: string
          created_by?: string | null
          evidence_kind?: Database["public"]["Enums"]["evidence_kind"] | null
          geo_region_id?: string | null
          geo_scope?: Database["public"]["Enums"]["evidence_geo_scope"] | null
          id?: string
          is_synthetic?: boolean
          language?: string | null
          licence?: string | null
          publication_date?: string | null
          publisher: string
          reference_url?: string | null
          review_due?: string | null
          source_class?: Database["public"]["Enums"]["evidence_source_class"]
          source_domain?: string | null
          source_type: Database["public"]["Enums"]["evidence_source_type"]
          status?: Database["public"]["Enums"]["evidence_status"]
          supersedes_id?: string | null
          syndromes?: Database["public"]["Enums"]["syndrome_category"][]
          title: string
          topics?: string[]
          trust_level?: Database["public"]["Enums"]["evidence_trust_level"]
          updated_at?: string
          valid_from?: string | null
          valid_until?: string | null
          verification_basis?: string[]
          verified_at?: string | null
          verified_by?: string | null
        }
        Update: {
          canonical_id?: string | null
          citation?: string | null
          content_hash?: string | null
          created_at?: string
          created_by?: string | null
          evidence_kind?: Database["public"]["Enums"]["evidence_kind"] | null
          geo_region_id?: string | null
          geo_scope?: Database["public"]["Enums"]["evidence_geo_scope"] | null
          id?: string
          is_synthetic?: boolean
          language?: string | null
          licence?: string | null
          publication_date?: string | null
          publisher?: string
          reference_url?: string | null
          review_due?: string | null
          source_class?: Database["public"]["Enums"]["evidence_source_class"]
          source_domain?: string | null
          source_type?: Database["public"]["Enums"]["evidence_source_type"]
          status?: Database["public"]["Enums"]["evidence_status"]
          supersedes_id?: string | null
          syndromes?: Database["public"]["Enums"]["syndrome_category"][]
          title?: string
          topics?: string[]
          trust_level?: Database["public"]["Enums"]["evidence_trust_level"]
          updated_at?: string
          valid_from?: string | null
          valid_until?: string | null
          verification_basis?: string[]
          verified_at?: string | null
          verified_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "evidence_items_geo_region_id_fkey"
            columns: ["geo_region_id"]
            isOneToOne: false
            referencedRelation: "regions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "evidence_items_supersedes_id_fkey"
            columns: ["supersedes_id"]
            isOneToOne: false
            referencedRelation: "evidence_items"
            referencedColumns: ["id"]
          },
        ]
      }
      evidence_topics: {
        Row: {
          active: boolean
          code: string
          created_at: string
          description: string
          label_en: string
        }
        Insert: {
          active?: boolean
          code: string
          created_at?: string
          description: string
          label_en: string
        }
        Update: {
          active?: boolean
          code?: string
          created_at?: string
          description?: string
          label_en?: string
        }
        Relationships: []
      }
      evidence_translations: {
        Row: {
          abstract: string | null
          created_at: string
          evidence_item_id: string
          id: string
          language: string
          provenance: string
          review_status: string
          reviewed_at: string | null
          reviewed_by: string | null
          title: string
        }
        Insert: {
          abstract?: string | null
          created_at?: string
          evidence_item_id: string
          id?: string
          language: string
          provenance: string
          review_status?: string
          reviewed_at?: string | null
          reviewed_by?: string | null
          title: string
        }
        Update: {
          abstract?: string | null
          created_at?: string
          evidence_item_id?: string
          id?: string
          language?: string
          provenance?: string
          review_status?: string
          reviewed_at?: string | null
          reviewed_by?: string | null
          title?: string
        }
        Relationships: [
          {
            foreignKeyName: "evidence_translations_evidence_item_id_fkey"
            columns: ["evidence_item_id"]
            isOneToOne: false
            referencedRelation: "evidence_items"
            referencedColumns: ["id"]
          },
        ]
      }
      evidence_versions: {
        Row: {
          abstract: string | null
          content_hash: string
          created_at: string
          evidence_item_id: string
          fetch_status: string
          id: string
          is_current: boolean
          licence_note: string | null
          retrieved_at: string | null
          source_last_modified: string | null
          version_label: string
        }
        Insert: {
          abstract?: string | null
          content_hash: string
          created_at?: string
          evidence_item_id: string
          fetch_status?: string
          id?: string
          is_current?: boolean
          licence_note?: string | null
          retrieved_at?: string | null
          source_last_modified?: string | null
          version_label: string
        }
        Update: {
          abstract?: string | null
          content_hash?: string
          created_at?: string
          evidence_item_id?: string
          fetch_status?: string
          id?: string
          is_current?: boolean
          licence_note?: string | null
          retrieved_at?: string | null
          source_last_modified?: string | null
          version_label?: string
        }
        Relationships: [
          {
            foreignKeyName: "evidence_versions_evidence_item_id_fkey"
            columns: ["evidence_item_id"]
            isOneToOne: false
            referencedRelation: "evidence_items"
            referencedColumns: ["id"]
          },
        ]
      }
      explanation_citations: {
        Row: {
          anchor_verified: boolean
          bundle_item_id: string
          claim_index: number
          created_at: string
          explanation_id: string
          id: string
          quote: string | null
          support_check: Json
        }
        Insert: {
          anchor_verified?: boolean
          bundle_item_id: string
          claim_index: number
          created_at?: string
          explanation_id: string
          id?: string
          quote?: string | null
          support_check?: Json
        }
        Update: {
          anchor_verified?: boolean
          bundle_item_id?: string
          claim_index?: number
          created_at?: string
          explanation_id?: string
          id?: string
          quote?: string | null
          support_check?: Json
        }
        Relationships: [
          {
            foreignKeyName: "explanation_citations_bundle_item_id_fkey"
            columns: ["bundle_item_id"]
            isOneToOne: false
            referencedRelation: "evidence_bundle_items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "explanation_citations_explanation_id_fkey"
            columns: ["explanation_id"]
            isOneToOne: false
            referencedRelation: "generated_explanations"
            referencedColumns: ["id"]
          },
        ]
      }
      generated_explanation_raw: {
        Row: {
          created_at: string
          explanation_id: string
          raw: string
        }
        Insert: {
          created_at?: string
          explanation_id: string
          raw: string
        }
        Update: {
          created_at?: string
          explanation_id?: string
          raw?: string
        }
        Relationships: [
          {
            foreignKeyName: "generated_explanation_raw_explanation_id_fkey"
            columns: ["explanation_id"]
            isOneToOne: true
            referencedRelation: "generated_explanations"
            referencedColumns: ["id"]
          },
        ]
      }
      generated_explanations: {
        Row: {
          bundle_id: string
          citation_status: string
          created_at: string
          id: string
          input_hash: string
          language: string
          model: string
          model_version: string | null
          output: Json | null
          params: Json
          prompt_version: string
          provider: string
          status: string
          validation_report: Json
        }
        Insert: {
          bundle_id: string
          citation_status?: string
          created_at?: string
          id?: string
          input_hash: string
          language?: string
          model: string
          model_version?: string | null
          output?: Json | null
          params?: Json
          prompt_version: string
          provider: string
          status: string
          validation_report?: Json
        }
        Update: {
          bundle_id?: string
          citation_status?: string
          created_at?: string
          id?: string
          input_hash?: string
          language?: string
          model?: string
          model_version?: string | null
          output?: Json | null
          params?: Json
          prompt_version?: string
          provider?: string
          status?: string
          validation_report?: Json
        }
        Relationships: [
          {
            foreignKeyName: "generated_explanations_bundle_id_fkey"
            columns: ["bundle_id"]
            isOneToOne: false
            referencedRelation: "evidence_bundles"
            referencedColumns: ["id"]
          },
        ]
      }
      health_reports: {
        Row: {
          age_band: Database["public"]["Enums"]["age_band"]
          case_count: number
          client_submission_id: string
          created_at: string
          free_text: string | null
          id: string
          language: string
          observed_at: string
          privacy_level: Database["public"]["Enums"]["privacy_level"]
          processing_status: Database["public"]["Enums"]["processing_status"]
          region_id: string
          report_type: Database["public"]["Enums"]["report_type"]
          severity: Database["public"]["Enums"]["report_severity"]
          source_type: Database["public"]["Enums"]["source_type"]
          submitted_by: string | null
          symptom_codes: string[]
          syndrome: Database["public"]["Enums"]["syndrome_category"]
          synthetic_batch: string | null
          updated_at: string
        }
        Insert: {
          age_band?: Database["public"]["Enums"]["age_band"]
          case_count?: number
          client_submission_id?: string
          created_at?: string
          free_text?: string | null
          id?: string
          language?: string
          observed_at: string
          privacy_level?: Database["public"]["Enums"]["privacy_level"]
          processing_status?: Database["public"]["Enums"]["processing_status"]
          region_id: string
          report_type?: Database["public"]["Enums"]["report_type"]
          severity?: Database["public"]["Enums"]["report_severity"]
          source_type: Database["public"]["Enums"]["source_type"]
          submitted_by?: string | null
          symptom_codes?: string[]
          syndrome: Database["public"]["Enums"]["syndrome_category"]
          synthetic_batch?: string | null
          updated_at?: string
        }
        Update: {
          age_band?: Database["public"]["Enums"]["age_band"]
          case_count?: number
          client_submission_id?: string
          created_at?: string
          free_text?: string | null
          id?: string
          language?: string
          observed_at?: string
          privacy_level?: Database["public"]["Enums"]["privacy_level"]
          processing_status?: Database["public"]["Enums"]["processing_status"]
          region_id?: string
          report_type?: Database["public"]["Enums"]["report_type"]
          severity?: Database["public"]["Enums"]["report_severity"]
          source_type?: Database["public"]["Enums"]["source_type"]
          submitted_by?: string | null
          symptom_codes?: string[]
          syndrome?: Database["public"]["Enums"]["syndrome_category"]
          synthetic_batch?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "health_reports_region_id_fkey"
            columns: ["region_id"]
            isOneToOne: false
            referencedRelation: "regions"
            referencedColumns: ["id"]
          },
        ]
      }
      privacy_settings: {
        Row: {
          description: string
          key: string
          updated_at: string
          value_int: number
        }
        Insert: {
          description: string
          key: string
          updated_at?: string
          value_int: number
        }
        Update: {
          description?: string
          key?: string
          updated_at?: string
          value_int?: number
        }
        Relationships: []
      }
      profiles: {
        Row: {
          created_at: string
          display_name: string | null
          id: string
          preferred_language: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          display_name?: string | null
          id: string
          preferred_language?: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          display_name?: string | null
          id?: string
          preferred_language?: string
          updated_at?: string
        }
        Relationships: []
      }
      regions: {
        Row: {
          active: boolean
          administrative_code: string | null
          created_at: string
          id: string
          is_synthetic: boolean
          name: string
          name_local: Json
          parent_region_id: string | null
          region_type: Database["public"]["Enums"]["region_type"]
          updated_at: string
        }
        Insert: {
          active?: boolean
          administrative_code?: string | null
          created_at?: string
          id?: string
          is_synthetic?: boolean
          name: string
          name_local?: Json
          parent_region_id?: string | null
          region_type: Database["public"]["Enums"]["region_type"]
          updated_at?: string
        }
        Update: {
          active?: boolean
          administrative_code?: string | null
          created_at?: string
          id?: string
          is_synthetic?: boolean
          name?: string
          name_local?: Json
          parent_region_id?: string | null
          region_type?: Database["public"]["Enums"]["region_type"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "regions_parent_region_id_fkey"
            columns: ["parent_region_id"]
            isOneToOne: false
            referencedRelation: "regions"
            referencedColumns: ["id"]
          },
        ]
      }
      report_aggregates: {
        Row: {
          case_count: number
          computed_at: string
          id: string
          min_cell_size_applied: number
          observed_date: string
          privacy_level: Database["public"]["Enums"]["privacy_level"]
          region_id: string
          report_count: number
          suppressed: boolean
          syndrome: Database["public"]["Enums"]["syndrome_category"]
        }
        Insert: {
          case_count: number
          computed_at?: string
          id?: string
          min_cell_size_applied: number
          observed_date: string
          privacy_level?: Database["public"]["Enums"]["privacy_level"]
          region_id: string
          report_count: number
          suppressed: boolean
          syndrome: Database["public"]["Enums"]["syndrome_category"]
        }
        Update: {
          case_count?: number
          computed_at?: string
          id?: string
          min_cell_size_applied?: number
          observed_date?: string
          privacy_level?: Database["public"]["Enums"]["privacy_level"]
          region_id?: string
          report_count?: number
          suppressed?: boolean
          syndrome?: Database["public"]["Enums"]["syndrome_category"]
        }
        Relationships: [
          {
            foreignKeyName: "report_aggregates_region_id_fkey"
            columns: ["region_id"]
            isOneToOne: false
            referencedRelation: "regions"
            referencedColumns: ["id"]
          },
        ]
      }
      report_signal_links: {
        Row: {
          aggregate_id: string | null
          created_at: string
          id: string
          observation_id: string | null
          signal_candidate_id: string
        }
        Insert: {
          aggregate_id?: string | null
          created_at?: string
          id?: string
          observation_id?: string | null
          signal_candidate_id: string
        }
        Update: {
          aggregate_id?: string | null
          created_at?: string
          id?: string
          observation_id?: string | null
          signal_candidate_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "report_signal_links_aggregate_id_fkey"
            columns: ["aggregate_id"]
            isOneToOne: false
            referencedRelation: "report_aggregates"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "report_signal_links_observation_id_fkey"
            columns: ["observation_id"]
            isOneToOne: false
            referencedRelation: "deidentified_observations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "report_signal_links_signal_candidate_id_fkey"
            columns: ["signal_candidate_id"]
            isOneToOne: false
            referencedRelation: "signal_candidates"
            referencedColumns: ["id"]
          },
        ]
      }
      retrieval_runs: {
        Row: {
          as_of_date: string
          corpus_snapshot_id: string
          error: string | null
          finished_at: string | null
          id: string
          queries: Json
          query_vocab_version: string
          retrieval_config_hash: string
          retrieval_version: string
          signal_candidate_id: string
          started_at: string
          stats: Json
          status: string
        }
        Insert: {
          as_of_date: string
          corpus_snapshot_id: string
          error?: string | null
          finished_at?: string | null
          id?: string
          queries?: Json
          query_vocab_version: string
          retrieval_config_hash: string
          retrieval_version: string
          signal_candidate_id: string
          started_at?: string
          stats?: Json
          status?: string
        }
        Update: {
          as_of_date?: string
          corpus_snapshot_id?: string
          error?: string | null
          finished_at?: string | null
          id?: string
          queries?: Json
          query_vocab_version?: string
          retrieval_config_hash?: string
          retrieval_version?: string
          signal_candidate_id?: string
          started_at?: string
          stats?: Json
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "retrieval_runs_corpus_snapshot_id_fkey"
            columns: ["corpus_snapshot_id"]
            isOneToOne: false
            referencedRelation: "corpus_snapshots"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "retrieval_runs_signal_candidate_id_fkey"
            columns: ["signal_candidate_id"]
            isOneToOne: false
            referencedRelation: "signal_candidates"
            referencedColumns: ["id"]
          },
        ]
      }
      signal_candidates: {
        Row: {
          baseline_value: number | null
          confidence: number | null
          created_at: string
          created_by: string | null
          detection_method: string
          deviation: number | null
          episode_key: string | null
          evidence: Json | null
          explanation: string | null
          first_detected_on: string | null
          first_run_id: string | null
          id: string
          last_run_id: string | null
          last_seen_on: string | null
          minimum_sample_count: number
          observed_value: number
          origin: Database["public"]["Enums"]["signal_origin"]
          region_id: string
          resolved_at: string | null
          review_note: string | null
          reviewed_at: string | null
          reviewed_by: string | null
          sample_count: number | null
          score_components: Json | null
          signal_score: number | null
          status: Database["public"]["Enums"]["signal_status"]
          syndrome: Database["public"]["Enums"]["syndrome_category"]
          time_window_end: string
          time_window_start: string
          updated_at: string
          verification_status: Database["public"]["Enums"]["verification_status"]
        }
        Insert: {
          baseline_value?: number | null
          confidence?: number | null
          created_at?: string
          created_by?: string | null
          detection_method?: string
          deviation?: number | null
          episode_key?: string | null
          evidence?: Json | null
          explanation?: string | null
          first_detected_on?: string | null
          first_run_id?: string | null
          id?: string
          last_run_id?: string | null
          last_seen_on?: string | null
          minimum_sample_count?: number
          observed_value: number
          origin?: Database["public"]["Enums"]["signal_origin"]
          region_id: string
          resolved_at?: string | null
          review_note?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          sample_count?: number | null
          score_components?: Json | null
          signal_score?: number | null
          status?: Database["public"]["Enums"]["signal_status"]
          syndrome: Database["public"]["Enums"]["syndrome_category"]
          time_window_end: string
          time_window_start: string
          updated_at?: string
          verification_status?: Database["public"]["Enums"]["verification_status"]
        }
        Update: {
          baseline_value?: number | null
          confidence?: number | null
          created_at?: string
          created_by?: string | null
          detection_method?: string
          deviation?: number | null
          episode_key?: string | null
          evidence?: Json | null
          explanation?: string | null
          first_detected_on?: string | null
          first_run_id?: string | null
          id?: string
          last_run_id?: string | null
          last_seen_on?: string | null
          minimum_sample_count?: number
          observed_value?: number
          origin?: Database["public"]["Enums"]["signal_origin"]
          region_id?: string
          resolved_at?: string | null
          review_note?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          sample_count?: number | null
          score_components?: Json | null
          signal_score?: number | null
          status?: Database["public"]["Enums"]["signal_status"]
          syndrome?: Database["public"]["Enums"]["syndrome_category"]
          time_window_end?: string
          time_window_start?: string
          updated_at?: string
          verification_status?: Database["public"]["Enums"]["verification_status"]
        }
        Relationships: [
          {
            foreignKeyName: "signal_candidates_detection_method_fkey"
            columns: ["detection_method"]
            isOneToOne: false
            referencedRelation: "detection_methods"
            referencedColumns: ["code"]
          },
          {
            foreignKeyName: "signal_candidates_first_run_id_fkey"
            columns: ["first_run_id"]
            isOneToOne: false
            referencedRelation: "detector_runs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "signal_candidates_last_run_id_fkey"
            columns: ["last_run_id"]
            isOneToOne: false
            referencedRelation: "detector_runs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "signal_candidates_region_id_fkey"
            columns: ["region_id"]
            isOneToOne: false
            referencedRelation: "regions"
            referencedColumns: ["id"]
          },
        ]
      }
      signal_evidence: {
        Row: {
          created_at: string
          evidence_item_id: string
          relevance_note: string | null
          signal_candidate_id: string
        }
        Insert: {
          created_at?: string
          evidence_item_id: string
          relevance_note?: string | null
          signal_candidate_id: string
        }
        Update: {
          created_at?: string
          evidence_item_id?: string
          relevance_note?: string | null
          signal_candidate_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "signal_evidence_evidence_item_id_fkey"
            columns: ["evidence_item_id"]
            isOneToOne: false
            referencedRelation: "evidence_items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "signal_evidence_signal_candidate_id_fkey"
            columns: ["signal_candidate_id"]
            isOneToOne: false
            referencedRelation: "signal_candidates"
            referencedColumns: ["id"]
          },
        ]
      }
      symptom_terms: {
        Row: {
          active: boolean
          code: string
          created_at: string
          label_en: string
          label_hi: string | null
          label_or: string | null
          syndrome_hint: Database["public"]["Enums"]["syndrome_category"] | null
        }
        Insert: {
          active?: boolean
          code: string
          created_at?: string
          label_en: string
          label_hi?: string | null
          label_or?: string | null
          syndrome_hint?:
            | Database["public"]["Enums"]["syndrome_category"]
            | null
        }
        Update: {
          active?: boolean
          code?: string
          created_at?: string
          label_en?: string
          label_hi?: string | null
          label_or?: string | null
          syndrome_hint?:
            | Database["public"]["Enums"]["syndrome_category"]
            | null
        }
        Relationships: []
      }
      user_roles: {
        Row: {
          created_at: string
          granted_by: string | null
          id: string
          region_id: string | null
          role: Database["public"]["Enums"]["app_role"]
          user_id: string
        }
        Insert: {
          created_at?: string
          granted_by?: string | null
          id?: string
          region_id?: string | null
          role: Database["public"]["Enums"]["app_role"]
          user_id: string
        }
        Update: {
          created_at?: string
          granted_by?: string | null
          id?: string
          region_id?: string | null
          role?: Database["public"]["Enums"]["app_role"]
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_roles_region_id_fkey"
            columns: ["region_id"]
            isOneToOne: false
            referencedRelation: "regions"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      admin_list_users: {
        Args: { _limit?: number; _offset?: number }
        Returns: {
          created_at: string
          display_name: string
          email: string
          roles: Database["public"]["Enums"]["app_role"][]
          user_id: string
        }[]
      }
      admin_set_user_region_scope: {
        Args: {
          _region_id: string
          _role: Database["public"]["Enums"]["app_role"]
          _target: string
        }
        Returns: undefined
      }
      admin_set_user_role: {
        Args: {
          _grant: boolean
          _role: Database["public"]["Enums"]["app_role"]
          _target: string
        }
        Returns: undefined
      }
      apply_report_retention: { Args: never; Returns: Json }
      deidentify_pending_reports: { Args: { _limit?: number }; Returns: number }
      detection_daily_features: {
        Args: { _from: string; _to: string }
        Returns: Json
      }
      get_report_aggregates: {
        Args: { _from: string; _region_id: string; _to: string }
        Returns: {
          case_count: number
          observed_date: string
          region_id: string
          report_count: number
          suppressed: boolean
          syndrome: Database["public"]["Enums"]["syndrome_category"]
        }[]
      }
      has_role: {
        Args: {
          _role: Database["public"]["Enums"]["app_role"]
          _user_id: string
        }
        Returns: boolean
      }
      is_region_in_scope: {
        Args: {
          _region_id: string
          _role: Database["public"]["Enums"]["app_role"]
          _user_id: string
        }
        Returns: boolean
      }
      refresh_report_aggregates: {
        Args: { _from: string; _to: string }
        Returns: number
      }
      region_subtree: {
        Args: { _root: string }
        Returns: {
          id: string
        }[]
      }
      review_signal_candidate: {
        Args: {
          _new_status: Database["public"]["Enums"]["signal_status"]
          _note?: string
          _signal_id: string
          _verification: Database["public"]["Enums"]["verification_status"]
        }
        Returns: {
          baseline_value: number | null
          confidence: number | null
          created_at: string
          created_by: string | null
          detection_method: string
          deviation: number | null
          episode_key: string | null
          evidence: Json | null
          explanation: string | null
          first_detected_on: string | null
          first_run_id: string | null
          id: string
          last_run_id: string | null
          last_seen_on: string | null
          minimum_sample_count: number
          observed_value: number
          origin: Database["public"]["Enums"]["signal_origin"]
          region_id: string
          resolved_at: string | null
          review_note: string | null
          reviewed_at: string | null
          reviewed_by: string | null
          sample_count: number | null
          score_components: Json | null
          signal_score: number | null
          status: Database["public"]["Enums"]["signal_status"]
          syndrome: Database["public"]["Enums"]["syndrome_category"]
          time_window_end: string
          time_window_start: string
          updated_at: string
          verification_status: Database["public"]["Enums"]["verification_status"]
        }
        SetofOptions: {
          from: "*"
          to: "signal_candidates"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      upsert_detected_signal: { Args: { _p: Json }; Returns: Json }
      write_audit: {
        Args: {
          _action: string
          _actor: string
          _entity: string
          _entity_id: string
          _metadata: Json
        }
        Returns: undefined
      }
    }
    Enums: {
      age_band:
        | "age_0_4"
        | "age_5_17"
        | "age_18_44"
        | "age_45_59"
        | "age_60_plus"
        | "age_unknown"
      app_role: "citizen" | "clinician" | "officer" | "admin"
      evidence_geo_scope:
        | "global"
        | "regional"
        | "national"
        | "state"
        | "district"
      evidence_kind:
        | "operational_guidance"
        | "case_definition"
        | "clinical_epidemiology_reference"
        | "situation_report"
        | "surveillance_data"
        | "research"
      evidence_source_class:
        | "intergovernmental_health_authority"
        | "national_government_health_agency"
        | "state_government_health_agency"
        | "peer_reviewed_literature"
        | "recognized_institution"
        | "professional_society_guideline"
        | "other_verified"
        | "unverified"
      evidence_source_type:
        | "guideline"
        | "government_advisory"
        | "peer_reviewed"
        | "situation_report"
        | "dataset"
        | "other"
      evidence_status:
        | "draft"
        | "quarantined"
        | "current"
        | "superseded"
        | "withdrawn"
        | "historical"
      evidence_trust_level: "unreviewed" | "reviewed" | "trusted"
      privacy_level: "raw" | "deidentified" | "aggregated"
      processing_status: "received" | "validated" | "deidentified" | "rejected"
      region_type: "country" | "state" | "district" | "block" | "locality"
      report_severity: "unknown" | "mild" | "moderate" | "severe"
      report_type: "individual_observation" | "aggregate_count"
      signal_origin: "system_detector" | "officer_manual" | "imported"
      signal_status:
        | "candidate"
        | "under_review"
        | "verified"
        | "monitoring"
        | "resolved"
        | "dismissed"
      source_type:
        | "citizen"
        | "clinician"
        | "health_facility"
        | "public_health_officer"
        | "survey"
        | "environmental"
        | "imported_dataset"
        | "system_generated"
      syndrome_category:
        | "acute_diarrhoeal_illness"
        | "fever"
        | "fever_with_rash"
        | "jaundice"
        | "respiratory_illness"
        | "other"
        | "unknown"
      verification_status:
        | "unverified"
        | "in_progress"
        | "supported"
        | "not_supported"
        | "inconclusive"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      age_band: [
        "age_0_4",
        "age_5_17",
        "age_18_44",
        "age_45_59",
        "age_60_plus",
        "age_unknown",
      ],
      app_role: ["citizen", "clinician", "officer", "admin"],
      evidence_geo_scope: [
        "global",
        "regional",
        "national",
        "state",
        "district",
      ],
      evidence_kind: [
        "operational_guidance",
        "case_definition",
        "clinical_epidemiology_reference",
        "situation_report",
        "surveillance_data",
        "research",
      ],
      evidence_source_class: [
        "intergovernmental_health_authority",
        "national_government_health_agency",
        "state_government_health_agency",
        "peer_reviewed_literature",
        "recognized_institution",
        "professional_society_guideline",
        "other_verified",
        "unverified",
      ],
      evidence_source_type: [
        "guideline",
        "government_advisory",
        "peer_reviewed",
        "situation_report",
        "dataset",
        "other",
      ],
      evidence_status: [
        "draft",
        "quarantined",
        "current",
        "superseded",
        "withdrawn",
        "historical",
      ],
      evidence_trust_level: ["unreviewed", "reviewed", "trusted"],
      privacy_level: ["raw", "deidentified", "aggregated"],
      processing_status: ["received", "validated", "deidentified", "rejected"],
      region_type: ["country", "state", "district", "block", "locality"],
      report_severity: ["unknown", "mild", "moderate", "severe"],
      report_type: ["individual_observation", "aggregate_count"],
      signal_origin: ["system_detector", "officer_manual", "imported"],
      signal_status: [
        "candidate",
        "under_review",
        "verified",
        "monitoring",
        "resolved",
        "dismissed",
      ],
      source_type: [
        "citizen",
        "clinician",
        "health_facility",
        "public_health_officer",
        "survey",
        "environmental",
        "imported_dataset",
        "system_generated",
      ],
      syndrome_category: [
        "acute_diarrhoeal_illness",
        "fever",
        "fever_with_rash",
        "jaundice",
        "respiratory_illness",
        "other",
        "unknown",
      ],
      verification_status: [
        "unverified",
        "in_progress",
        "supported",
        "not_supported",
        "inconclusive",
      ],
    },
  },
} as const
